### ISSUE TITLE
Import/Export feature request

### ISSUE THREAD

**Issue by denisborovikov** [fawadasaurus/d4-aspect-tracker#14]
1. Clean up stored data (storing a date in the local storage for every aspect seems excessive)
2. Store data in a single local storage entry
3. Implement Import/Export to save data and transfer between devices.

**Comment by fawadasaurus** [comment]
I had it in a single local storage entry before but it seemed excessive to reload all owned aspects when I only wanted to update a single aspect at a time. Then one time my data corrupted and it all got overwritten in a single click. I don't want that happening again. 

I agree that time is no longer needed. It was an idea that perhaps a timeline view would be useful but I can't think of a real reason for it anymore. 

Import/export is a good idea. I've been thinking if there was a way to use oauth and use a 3rd party provider to transfer / sync the data automatically.

Ex: sign in with google and it will automatically create a google sheet in your google drive to save your data

**Comment by denisborovikov** [comment]
There are only about 200 aspects in the game. Local storage is pretty fast, so there's no difference if you store all aspects in one entry or different. If we implement import/export, data corruption shouldn't be an issue. 

I don't know if using external storage is a good idea. The implementation seems too complex. If data is corrupted, the external storage will also be corrupted if it doesn't support versioning.

We can use a simple JSON format to import/export via file/clipboard or put the whole storage into a URL so users can share the link and open it on another device.

**Comment by Thilusmh** [comment]
Just a layman commenting here, but wanted to bump this for interest. I switch between a home and work computer every day, and that alone keeps me from using this otherwise awesome tool. Any method of saving/loading would be great: obviously an automatic sync via a login would be the best, but even a JSON import/export would be a nice option. One of the D4 map trackers does that, and I just save the JSON to my shared OneDrive so it's accessible anywhere. Obviously just one use case, but throwing it in as an example =)

**Comment by fawadasaurus** [comment]
Yea. Give me a couple days to see if I can think of something creative. Otherwise I'll implement a basic export/import function. 

Need to make the payloads smaller to do that so I'll first start by making payloads smaller (no more time entries).

I'm not convinced to change the storage back to a single field though. It seems ripe for race conditions like what I suspect initially corrupted my data.

**Comment by johniebravo** [comment]
Love the app. Interested in this as well. Concerned i will lose all my inventory at the site if I clear my cache and would like some way to export the data, or save to cloud.

**Comment by fawadasaurus** [comment]
Added a simple import/export button. It will overwrite all your aspects if you import, so be careful.

I tried to get creative but asynchronous/manual multi-directional synchronization is complicated.

**Comment by johniebravo** [comment]
thank you!

**Comment by Thilusmh** [comment]
> 

Yes indeed it is =P
But thank you for this: it's going to be invaluable going into Season 1, I think!

**Comment by fawadasaurus** [comment]
I use this tool every time I play so I'm glad that there are others who also find this valuable.
