### ISSUE TITLE
QOL improvements

### ISSUE THREAD

**Issue by denisborovikov** [fawadasaurus/d4-aspect-tracker#5]
Hey, thanks for the tracker!  I looked for something similar and found your post on Reddit. I pulled your code and made some changes locally. I'm unfamiliar with Svelte, Tailwind, and Flowbite, but I got this.

Most notable changes

- Fixed zoom and horizontal scroll on mobile.
- Cleaned up space and made UI more mobile-friendly.
- Switched to a dark color scheme (feels more appropriate for Diablo).
- Added buttons for 2-handed weapons and amulets (fixes #1 ). The entered value is automatically divided.
- Input allows only numbers and shows a numeric keyboard on mobile.
- Owned aspect values are sorted from big to small.
- Replaced curly brackets with square ones and replaced `/` with `-` for better readability.
- Moved codex to the title, i.e. `of Berserk Ripping , Offensive (Codex)`

Feel free to let me know if you're interested in some or all updates, I'm glad to submit a PR.

![image](https://github.com/fawadasaurus/d4-aspect-tracker/assets/831065/e00ca1a6-ffb7-4e1e-9901-41df5df556a3)

**Comment by fawadasaurus** [comment]
Very cool.  Thanks!

I think the only thing that I am not a fan is the `Input allows only numbers and shows a numeric keyboard on mobile.` because there are a couple aspects that have multiple values.  When I entered them I put a comma between. Other people may be doing something else or adding other values in the notes.

One thing that I found myself doing is that I put a letter G (gloves) H (head) etc, in each note to let me know what type of item it was on to make it easier to find the aspect in my stash.  I will add a task to think of a better solution to finding items in the stash.

I would be happy to accept your PR (excluding the number-only) change.

**Comment by denisborovikov** [comment]
Got it. In this case, I need to revert the 2-hand/amulet buttons as well, because the input value can be anything, not only a number. Let me create the PR with the complete list of changes, you can review and suggest changes afterwards.
